# Generated by Django 2.0.2 on 2018-05-08 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('brands', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrition_grade', models.FloatField(blank=True, null=True)),
                ('main_category', models.CharField(blank=True, max_length=100, null=True)),
                ('productimageurl', models.CharField(blank=True, db_column='productImageUrl', max_length=200, null=True)),
                ('productimagethumburl', models.CharField(blank=True, db_column='productImageThumbUrl', max_length=200, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purbeurre.Categories')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purbeurre.Products')),
            ],
            options={
                'db_table': 'products_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_products',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'description', 'quantity')},
        ),
        migrations.AlterUniqueTogether(
            name='usersproducts',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productscategories',
            unique_together={('product', 'category')},
        ),
    ]
