# Generated by Django 2.0.2 on 2018-04-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('brands', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrition_grade', models.FloatField(blank=True, null=True)),
                ('main_category', models.CharField(blank=True, max_length=100, null=True)),
                ('productimageurl', models.CharField(blank=True, db_column='productImageUrl', max_length=200, null=True)),
                ('productimagethumburl', models.CharField(blank=True, db_column='productImageThumbUrl', max_length=200, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'products_categories',
                'managed': False,
            },
        ),
    ]
