# Generated by Django 2.0.2 on 2018-05-08 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purbeurre.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'users_products',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usersproducts',
            unique_together={('user', 'product')},
        ),
    ]
