# Generated by Django 2.0.2 on 2018-02-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
