# Generated by Django 2.0.2 on 2018-05-08 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0003_auto_20180508_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersproducts',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Products'),
        ),
        migrations.AlterField(
            model_name='usersproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
